### ISSUE TITLE
Null* times MarshalJSON and UnmarshalJSON

### ISSUE THREAD

**Issue by derkan** [samonzeweb/godb#18]
Hi Samuel,

In my first pull request for `types`, I've added wrappers around `sql.Null*` types, but later we removed these wrappers to use directly `sql.Null*` types. But `sql.Null*` types don't have `MarshalJSON` and `UnmarshalJSON`  methods, which makes json data handling a problem. Also `types.NullTime` does not have such methods.

Is it OK to add wrappers for `sql.Null*` types again for `MarshalJSON` and `UnmarshalJSON` methods? 

If it is OK I'll create a pull request for json compatibility to all(`types.Null*`, `sql.Null*`), if not I'll create a pull request for json compatibility to only our types(`types.Null*`).

**Comment by samonzeweb** [comment]
Hi derkan,

I'm on holiday, I'll get back in two weeks  and will not review anything before. I've no computer with me. And need to do anything except dev tasks ;)

But I think you can add types if needed. Take all your time to write docs, tests, ... as I'm not available. I'll try to review this near mid august.

Sam.

**Comment by samonzeweb** [comment]
As the PR was merged ( https://github.com/samonzeweb/godb/pull/19 ), can I close this issue ?

**Comment by derkan** [comment]
Yes please.
Thanks!
