### ISSUE TITLE
Need better UUID/GUID support

### ISSUE THREAD

**Issue by finsterdexter** [samonzeweb/godb#20]
We use uuid as primary keys in Postgres, and this probably applies to GUID types in MS SQL Server. Things like hard-coded int64 primary keys (both Do and DoWithReturning on *InsertStatement) make it kind of a pain to work with. So, humbly requesting this feature.

**Comment by samonzeweb** [comment]
Hi,

Thanks for your proposition.

I'll study it later (at least two weeks) as i'm on holidays, without laptop.

There is no standard type in Go for UUID/GUID, just public packages. What are you using ? 

Sam.

**Comment by finsterdexter** [comment]
We're using github.com/gofrs/uuid, which IIRC is a fork satoshi/uuid.

**Comment by finsterdexter** [comment]
Thank you, we will look over this and see what we can figure out.
