### ISSUE TITLE
White/Black list support for struct Update/Insert

### ISSUE THREAD

**Issue by derkan** [samonzeweb/godb#22]
Hi Sam,

Without w/b listing struct insert/update becomes useless and forces developer to use InsertInto/UpdateInto methods which results in lots of boilerplate code. So #21 is to resolve this.

Can you review #21?

Erkan.

**Comment by samonzeweb** [comment]
Hi Derkan,

I'll see it next week (perhaps next week-end). Of course before if I find time (I'll try).

My first reaction when I saw the first lines of code yesterday was : WHY ? My personal opinion is : the data layer don't have to filter data, it has to be done by upper layers, and often API data aren't exactly the same as DB data.

Then I'm interested about your use case and your motivation about this implementation. I've an idea as your works on json serialization/deserialization, but not totally sure.

In any case I think it could by useful to somebody even if it's not my own way to do things, no problem with that. I'm just curious about how other people works.

Sam.

**Comment by samonzeweb** [comment]
Code review done, I just found a little bug.

**Comment by samonzeweb** [comment]
PR merged.
