### ISSUE TITLE
Standardization of common errors for db backends

### ISSUE THREAD

**Issue by derkan** [samonzeweb/godb#25]
Hi Sam,

GODB supports multiple DB backends, but developing for multiple databases needs common error handling. For example to check `UniqueConstraint` error you should check error message for current db connection(if targeting 4 db types, 4 different `if` checks...) and this leads to lots of boiler code.

#23 is to solve this problem. Not all errors are added, but some common errors are added. Can you review #23?

Erkan.

**Comment by samonzeweb** [comment]
Code review done, please see my comment and suggestion.
Thanks for this contribution  😀

**Comment by samonzeweb** [comment]
Merged !
