### ISSUE TITLE
Added Int64Slice,StrSlice,Float64Slice and BoolSlice

### ISSUE THREAD

**Issue by derkan** [samonzeweb/godb#28]
Hi Sam,

Please review #27 

Thanks,
Erkan.

**Comment by samonzeweb** [comment]
Hi Derkan,

Thanks for the PR. I made the review, only trivials things.

Sam.

**Comment by derkan** [comment]
Hi Sam, I corrected code according to your suggestions, please check.

**Comment by samonzeweb** [comment]
Checked and merged.
Thanks.
