### ISSUE TITLE
While trying to go get godb, unknown revision errors on golang.org/x/net

### ISSUE THREAD

**Issue by finsterdexter** [samonzeweb/godb#35]
Go version:
`go version go1.12.4 darwin/amd64`

Observed behavior:
```
~/go/src/github.com/myrepo/myproject % go get github.com/samonzeweb/godb
go: finding golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
go: finding golang.org/x/net v0.0.0-20181114220301-adae6a3d119a
go: golang.org/x/net@v0.0.0-20181114220301-adae6a3d119a: unknown revision adae6a3d119a
go: golang.org/x/net@v0.0.0-20190108225652-1e06a53dbb7e: unknown revision 1e06a53dbb7e
go: error loading module requirements
```

Expected behavior:
I expect that go get installs the module as intended.

**Comment by samonzeweb** [comment]
I tried to reproduce the behavior, without success.

I've done :

- Cleaning all assets generated or downloaded previously by Go
- Running all tests on all databases supported by godb
- Creating a separate project and `go get ...` 

My environment :

- Same Go version as yours (the latest one)
- Ubuntu 18.04 (but my last work on godb was done in OSX, without trouble)

None of the two last steps failed.

Do you have any complementary piece of information about you case ? Perhaps my separate project is too simple, if you have a minimal one to reproduce the behavior I could investigate more.

**Comment by finsterdexter** [comment]
Hmm, yeah my project is pretty minimal, right now, but I tried it on another PC and it was fine... must be something with my local setup. Sorry
