### ISSUE TITLE
Create new release with module changes

### ISSUE THREAD

**Issue by plopezm** [samonzeweb/godb#40]
Hello, Could you please create a new release with the go.mod fixes?

Thank you! :)

**Comment by samonzeweb** [comment]
Done.
You was just faster than me :laughing:

**Comment by samonzeweb** [comment]
Sorry... I've made a mistake. Work still need to be done....

**Comment by samonzeweb** [comment]
See v1.0.12 .

**Comment by plopezm** [comment]
> See v1.0.12 .

Thanks samonzeweb great job! :D
