### ISSUE TITLE
Local cache, remote DB

### ISSUE THREAD

**Issue by dolanor** [samonzeweb/godb#41]
Hi,

Could we think of some kind of cache driver that would be used as any other, but that would have some local copy of a DB in some SQLite. Of course, there would be some knobs to be able to configure when to consider a data stale and need to update the cache from the DB. But we should have some great default so no need to be knee deep in config to use it.
The big problem would be the consistency and sync, but someone looking for a solution like that would be aware of it.
Some system have limited connectivity, and having a reactive app even with stale data might be better than no answer/update at all.

For an extra integration, I could even think about some kind of integration with some REST-ful API transformed into local sqlite cache. Then a mobile app could always have some data in it without network. (this might be stupid and maybe a simple local HTTP cache could be smarter).
What do you think?

**Comment by samonzeweb** [comment]
Hi,

The idea seems interesting, but is it the right place ? Is it the role of godb ? (or other similar tool). The good place for this, IMO, is in a repository where you have full control of what can be cached, how long it can be, and what can't.

Integrating this cache management into the data access tool could save some lines of code, but you will have few control on it.

Admitting it's a good solution, there are some problems :
* you can't use it with raw sql queries, or only simplest ones, as they will not be compatible between different DB backends. But it depends on how you will manage the cache, perhaps you will use SQLite avec a k/v store based on SQL string.
* instances of godb use the given adapter features to build queries, not executing them. It could not be transparent for upper layers. Then, it could not be only an adapter stuff, other parts of godb have to be changed.

Sorry if my response isn't enthusiast, but I'm not sure it's a good idea in term of an application architecture, and it will probably be more complicated than just designing an adapter. Regarding the second point, perhaps you have thought more about it than me and have some interesting to suggest ?

**Comment by dolanor** [comment]
I completely get it. I might have a great vision of something nearly automated, but the amount of knobs and my ignorance of godb internal might make me unaware of those so many shortcomings. And cache is one of the hardest problem of computing. It must be for a reason.
If I successfully build something for a business use-case, I will try to extract the logic and put it in godb if it's agnostic enough.
