### ISSUE TITLE
Using one connection in several goroutines

### ISSUE THREAD

**Issue by plopezm** [samonzeweb/godb#44]
When a connection is reused between differents goroutines, sometimes there's a race condition with "db.consumedTime" attribute.

The workaround is to use a RWMutex, but, I don't know if you have something in mind.

If it is ok for you, I can create the merge request

**Comment by samonzeweb** [comment]
An instance of `godb.DB` isn't intended to be used by multiple goroutines. It's a small object, in each goroutine create a new instance with the `Clone` method : https://godoc.org/github.com/samonzeweb/godb#DB.Clone

It's an original design choice to avoid synchronizing too often (it has a cost in cpu/time and in complexity). Other parts than `consumedTime` could be badly effected.

But now I have to admit that it's not very clear in the documentation. The mention in the `Clone` doc isn't enough. Not explicit enough, and not obvious if you don't read all the doc. Something I have to fix.

Then my recommendation is not to *correct* `consumedTime` or any other part, but creating an *root* `godb.DB` instance and cloning it in each goroutine, sub-goroutine, ... (ie : in a http handler). Use the `Clear` method with a `defer` statement (not `Close`) : https://godoc.org/github.com/samonzeweb/godb#DB.Clear

**Comment by plopezm** [comment]
Perfect! Thank you :)
