### ISSUE TITLE
question: how exec join query 

### ISSUE THREAD

**Issue by tablecell** [samonzeweb/godb#52]
does  godb  support  join query
please  show some example

**Comment by derkan** [comment]
Example:
```go
type Author struct {
	ID        int    `db:"id" json:"id"`
	Firstname string `db:"firstname" json:"firstname"`
	Lastname  string `db:"lastname" json:"lastname"`
}

type Book struct {
	ID       int           `db:"id" json:"id"`
	AuthorID sql.NullInt64 `db:"author_id" json:"author_id"`
	Title    string        `db:"title" json:"title"`
}

type BookInfo struct {
	Book   `db:",rel=b" json:"book"`
	Author `db:",rel=a" json:"author"`
}
 // ....
var books []BookInfo
	err = db.SelectFrom("books as b").
		LeftJoin("authors", "a", godb.Q("b.author_id = a.id")).Do(&books)
```

**Comment by samonzeweb** [comment]
Thanks @derkan .

@tablecell, you can use LeftJoin (most useful for 0,1 or 1,1 relationship) ou InnerJoin . In last resort you can use a row statement : https://github.com/samonzeweb/godb/blob/master/dbtests/common/rawsql_tests.go

Please not that godb returns only 1 rowset, even with a join clause. It's not like ActiveRecord (Rails) or Entity Framework (.NET) whose return a graph a data. If you want something similar you have to do separate requests (if needed) ans rebuild a graph yourself.
